/**
 * Publisher sites: Acme (genuine) and Pro (lookalike).
 *
 * Both are plain static hosts — a catalog, resource cards and hosted attestations, exactly what
 * a real publisher exposes. Nothing here knows about trust; that is entirely the orchestrator's
 * job. Routing is by Host header, so both domains can share one HTTPS listener (they both
 * resolve to loopback in dev).
 *
 * Content is generated by `yarn seed`; this only serves it.
 */

import { createServer } from 'node:https'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'

import * as dotenv from 'dotenv'
import express from 'express'

import { ACME_DOMAIN, PRO_DOMAIN } from './shared/demo-config'
import { ensureDemoTls } from './sites/certs'

dotenv.config()

const PORT = Number(process.env.SITES_PORT ?? 443)
const STATIC_ROOT = resolve(process.cwd(), 'static')

const SITES: Record<string, string> = {
  [ACME_DOMAIN]: 'acme-site',
  [PRO_DOMAIN]: 'pro-site',
}

function hostname(header: string | undefined): string {
  return (header ?? '').split(':')[0].toLowerCase()
}

function main() {
  const missing = Object.values(SITES).filter(
    (site) => !existsSync(resolve(STATIC_ROOT, site, '.well-known/ai-catalog.json'))
  )
  if (missing.length) {
    throw new Error(`no catalog for ${missing.join(', ')} — run \`yarn seed\` first`)
  }

  const app = express()

  // Serve the catalog with its registered media type; ARD crawlers care.
  app.use((req, res, next) => {
    if (req.path.endsWith('/ai-catalog.json')) res.type('application/ai-catalog+json')
    else if (req.path.endsWith('.sd-jwt')) res.type('application/vc+sd-jwt')
    next()
  })

  app.use((req, res, next) => {
    const site = SITES[hostname(req.headers.host)]
    if (!site) {
      res.status(404).json({
        error: 'unknown publisher',
        detail: `Host "${hostname(req.headers.host)}" is not one of: ${Object.keys(SITES).join(', ')}`,
      })
      return
    }
    express.static(resolve(STATIC_ROOT, site), { dotfiles: 'allow', index: false })(req, res, next)
  })

  app.use((_req, res) => res.status(404).json({ error: 'not found' }))

  const tls = ensureDemoTls(Object.keys(SITES))
  createServer({ cert: tls.cert, key: tls.key }, app).listen(PORT, () => {
    console.log(`[sites] serving publisher sites on port ${PORT}`)
    for (const [domain, site] of Object.entries(SITES)) {
      console.log(`[sites]   https://${domain}${PORT === 443 ? '' : `:${PORT}`}/.well-known/ai-catalog.json  (${site})`)
    }
  })
}

try {
  main()
} catch (error) {
  console.error('[sites] FATAL', (error as Error)?.message ?? error)
  process.exit(1)
}
